//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progra1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular
    {
        public int idUsuario { get; set; }
        public string primerNombre { get; set; }
        public string apellidos { get; set; }
        public decimal cuentaBancaria { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
